<script setup>
import { computed, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { profile, projects, services, skills, savePortfolio } from '../data/portfolio'
import '../admin.css'
const section=ref('profile'),saved=ref(false)
const sections=[['profile','Profil','fa-solid fa-user'],['projects','Proyek','fa-solid fa-layer-group'],['skills','Keahlian','fa-solid fa-bolt'],['services','Layanan','fa-solid fa-briefcase']]
const slugify=value=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')
const save=()=>{savePortfolio();saved.value=true;setTimeout(()=>saved.value=false,2200)}
const addSkill=()=>skills.push(['fa-solid fa-code','Skill baru',70])
const addService=()=>services.push(['fa-solid fa-star','Layanan baru','Deskripsi layanan Anda.'])
const addProject=()=>projects.push({slug:`project-${Date.now()}`,title:'Proyek baru',category:'Website',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80',description:'Deskripsi singkat proyek.',long:'Ceritakan detail, tujuan, dan hasil proyek di sini.',tech:['Vue.js','CSS']})
const editProject=computed(()=>projects)
</script>
<template><main class="admin-page"><aside class="admin-sidebar"><RouterLink to="/" class="brand">MB<b>G</b></RouterLink><div><small>PORTFOLIO CMS</small><h2>Admin Panel</h2></div><nav class="admin-nav"><button v-for="[id,label,icon] in sections" :class="{active:section===id}" @click="section=id"><i :class="icon"/>{{label}}</button></nav><RouterLink to="/" class="back-site"><i class="fa-solid fa-arrow-left"/> Lihat website</RouterLink></aside><section class="admin-content"><header><div><p class="eyebrow">ADMINISTRASI KONTEN</p><h1>{{sections.find(x=>x[0]===section)[1]}}</h1></div><button class="button primary" @click="save"><i class="fa-solid fa-floppy-disk"/> Simpan perubahan</button></header><p v-if="saved" class="admin-success"><i class="fa-solid fa-circle-check"/> Tersimpan di browser Anda.</p>
<div v-show="section==='profile'" class="admin-card"><h3>Informasi utama</h3><p>Konten ini langsung muncul pada halaman utama dan kontak.</p><div class="form-grid"><label>Nama lengkap<input v-model="profile.name"/></label><label>Profesi / Role<input v-model="profile.role"/></label><label class="full">Headline<input v-model="profile.headline"/></label><label class="full">Deskripsi singkat<textarea v-model="profile.bio" rows="3"/></label><label class="full">Tentang saya<textarea v-model="profile.about" rows="4"/></label><label>Lokasi<input v-model="profile.location"/></label><label>Email<input v-model="profile.email" type="email"/></label><label>WhatsApp<input v-model="profile.whatsapp"/></label><label class="full">URL foto profil<input v-model="profile.image"/></label></div></div>
<div v-show="section==='projects'" class="admin-stack"><article v-for="(project,index) in editProject" :key="project.slug" class="admin-card"><div class="card-head"><h3>Proyek {{index+1}}</h3><button class="delete" @click="projects.splice(index,1)"><i class="fa-solid fa-trash"/> Hapus</button></div><div class="form-grid"><label>Nama proyek<input v-model="project.title" @input="project.slug=slugify(project.title)"/></label><label>Kategori<select v-model="project.category"><option>Website</option><option>Application</option><option>UI/UX</option></select></label><label class="full">URL gambar<input v-model="project.image"/></label><label class="full">Deskripsi singkat<textarea v-model="project.description" rows="2"/></label><label class="full">Detail proyek<textarea v-model="project.long" rows="3"/></label><label class="full">Teknologi (pisahkan dengan koma)<input :value="project.tech.join(', ')" @input="project.tech=$event.target.value.split(',').map(x=>x.trim()).filter(Boolean)"/></label></div></article><button class="add-row" @click="addProject"><i class="fa-solid fa-plus"/> Tambah proyek</button></div>
<div v-show="section==='skills'" class="admin-stack"><article v-for="(skill,index) in skills" :key="index" class="admin-card compact-row"><i :class="skill[0]"/><input v-model="skill[1]"/><input v-model.number="skill[2]" type="number" min="0" max="100"/><span>%</span><button class="delete icon-delete" @click="skills.splice(index,1)" aria-label="Hapus skill"><i class="fa-solid fa-trash"/></button></article><button class="add-row" @click="addSkill"><i class="fa-solid fa-plus"/> Tambah skill</button></div>
<div v-show="section==='services'" class="admin-stack"><article v-for="(service,index) in services" :key="index" class="admin-card"><div class="card-head"><h3>Layanan {{index+1}}</h3><button class="delete" @click="services.splice(index,1)"><i class="fa-solid fa-trash"/> Hapus</button></div><div class="form-grid"><label>Nama layanan<input v-model="service[1]"/></label><label>Icon Font Awesome<input v-model="service[0]"/></label><label class="full">Deskripsi<textarea v-model="service[2]" rows="3"/></label></div></article><button class="add-row" @click="addService"><i class="fa-solid fa-plus"/> Tambah layanan</button></div></section></main></template>
